FROM openjdk:17
WORKDIR /app
COPY . .
RUN chmod +x ./gradlew && ./gradlew build -x test
COPY build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","-Duser.timezone=Asia/Seoul","-Dspring.profiles.active=prod","app.jar"]
