FROM openjdk:17-slim-buster

RUN apt-get update && apt-get install -y findutils

WORKDIR /app
COPY . .
RUN chmod -R 755 /app
RUN chmod +x ./gradlew && ./gradlew build -x test

COPY build/libs/app.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "-Duser.timezone=Asia/Seoul", "-Dspring.profiles.active=prod", "app.jar"]