spring:
  application:
    name: ddada
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  graphql:
    cors:
      allowed-origins: ${ALLOWED_ORIGINS:*}
      allowed-methods: ${ALLOWED_METHODS:*}
      allowed-headers: ${ALLOWED_HEADERS:Origin,Access-Control-Allow-Origin}
      exposed-headers: ${EXPOSED_HEADERS:Authorization,Content-Type}
      allow-credentials: ${ALLOWED_CREDENTIALS:true}
      one-hour: 3600