spring:
  application:
    name: ddada
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  graphql:
    cors:
      allowed-origins: ${ALLOWED_ORIGINS:*}
      allowed-methods: ${ALLOWED_METHODS:*}
      allowed-headers: ${ALLOWED_HEADERS:Origin,Access-Control-Allow-Origin}
      exposed-headers: ${EXPOSED_HEADERS:Authorization,Content-Type}
      allow-credentials: ${ALLOWED_CREDENTIALS:true}
      one-hour: 3600
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret-key: ${SECRET_KEY}
  access-token-exp: ${ACCESS_TOKEN_EXP}
  refresh-token-exp: ${REFRESH_TOKEN_EXP}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${S3_REGION}
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

coolsms:
  apikey: ${COOLSMS_APIKEY}
  apisecret: ${COOLSMS_APISECRET}
  fromnumber: ${COOLSMS_FROMNUMBER}
